vector_store:
  type: "milvus"  # 或 "qdrant",milvus
  
  milvus:
    address: "10.18.150.1:19530"
    db_name: "default"
    collection: "qa"
    index:
      type: "HNSW"
      metric_type: "L2"
      nlist: 1024

  qdrant:
    address: "http://120.24.61.231:16333"
    Host: "192.168.1.158"
    Port: 6334
    collection: "qa"

ollama:
  address: "http://192.168.1.228:11434"
  llm_model: "qwen2.5:7b"
  embedder_model: "nomic-embed-text:latest"
  temperature: 0.8

processing:
  chunk_size: 50
  chunk_overlap: 0
  top_k: 5
  score_threshold: 0.5

mysql:
  dsn: "root:123456@tcp(192.168.1.158:3307)/test?parseTime=true&charset=utf8mb4"

http:
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
