milvus:
  address: "10.18.150.1:19530"
  db_name: "default"
  collection: "text_collection"
  index:
    type: "IVF_FLAT"
    metric_type: "L2"
    nlist: 1024

ollama:
  address: "http://192.168.1.228:11434"
  llm_model: "qwen2.5:7b"
  embedder_model: "nomic-embed-text:latest"
  temperature: 0.8

processing:
  chunk_size: 50
  chunk_overlap: 0
  top_k: 5
  score_threshold: 0.5
